### ISSUE TITLE
Need an API for a custom plugin

### ISSUE THREAD

**Issue by Kira07** [NoChanceSD/PvPManager-Issues#1]
Hello,
My dev is making a plugin to prevent players to hide in their frontposts during combat and need to 'connect' with PvpManager, could you please give me an API ?

**Comment by NoChanceSD** [comment]
Not exactly an API but this class should provide everything he needs: https://github.com/NoChanceSD/PvPManager/blob/master/PvPManager/src/main/java/me/NoChance/PvPManager/PvPlayer.java
That class remains mostly the same in the premium version, i will deobfuscate it and add a static get method in PvPlayer taking a Player as argument in the next update.

**Comment by NoChanceSD** [comment]
Just uploaded the new version, let me know if it's enough for right now. I might provide other classes in the future.

**Comment by Kira07** [comment]
Thanks, but according to my dev the API breaks while used with the plugin..

2015-10-21 2:38 GMT+01:00 NoChanceSD <notifications@github.com>:

**Comment by NoChanceSD** [comment]
Did you give him the premium PvPManager jar? 
If not, that's what he should use to hook into. (I'm assuming you trust your dev and he won't be redistributing the jar)

**Comment by Kira07** [comment]
Yes I gave him the latest version of the premium PvPManager
(don't worry, he won't)

2015-10-22 15:16 GMT+01:00 NoChanceSD <notifications@github.com>:

**Comment by NoChanceSD** [comment]
In that case, it should work fine. Or what exactly breaks?

**Comment by Kira07** [comment]
He said "[23:33:18] Hijacking // Declared || FearPVP Owner: It just doesn't
load with the plugin
[23:33:21] Hijacking // Declared || FearPVP Owner: Though
[23:33:26] Hijacking // Declared || FearPVP Owner: I hook it in onenable
[23:33:27] Hijacking // Declared || FearPVP Owner: and
[23:33:32] Hijacking // Declared || FearPVP Owner: depend it in the
plugin.yml"

2015-10-22 22:44 GMT+01:00 NoChanceSD <notifications@github.com>:

**Comment by NoChanceSD** [comment]
Alright, it's probably some issue related with my obfuscation. I will try to get it fixed tomorrow.

**Comment by Kira07** [comment]
Alright, thank you

**Comment by Kira07** [comment]
Hello, anything new ?

2015-10-23 2:25 GMT+01:00 Kira <kingkira97@gmail.com>:

> Alright, thank you
>

**Comment by NoChanceSD** [comment]
Not yet, what is the error really? You didn't give me an error.

**Comment by Kira07** [comment]
"It literally doesn't register when I make it register, It says "the plugin
cant be found" though I make it depend at the start."

2015-10-25 0:38 GMT+01:00 NoChanceSD <notifications@github.com>:

**Comment by Kira07** [comment]
Anything new ?..

2015-10-25 15:47 GMT+01:00 Kira <kingkira97@gmail.com>:

**Comment by NoChanceSD** [comment]
Yes, there is no issue on my part.
Works fine using the static method on PvPlayer.

**Comment by Kira07** [comment]
Could you send how you hooked in ?

2015-11-02 21:53 GMT+01:00 NoChanceSD <notifications@github.com>:

**Comment by NoChanceSD** [comment]
So let´s say you have a Player p
Player p;

Get a PvPlayer using the static method
PvPlayer pp = PvPlayer.get(p);

Use the PvPlayer for whatever it's needed, examples:
System.out.println(pp.isInCombat());
System.out.println(pp.isNewbie());

**Comment by NoChanceSD** [comment]
Let me know if it worked (or not)

**Comment by Kira07** [comment]
Thanks, just told my dev, he'll try tomorrow

2015-11-05 3:45 GMT+01:00 NoChanceSD <notifications@github.com>:
