### ISSUE TITLE
Suggestion for command

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#10]
This is the only Github place I could find to make a suggestion.

A command which another plugin had was to grant pvp protection for a time to a player. It would be fairly simple: "/pvpmanager grant <name> <time>" players could also disable this with the command to remove protection.

A command like this would be helpful for when you want to grant a player pvp protection but not indefinitely.

**Comment by NoChanceSD** [comment]
This is the right place =P
Will work on this.

**Comment by NoChanceSD** [comment]
Added in v3.3.9
