### ISSUE TITLE
Server crash when tagged player logs out

### ISSUE THREAD

**Issue by Daphsquid** [NoChanceSD/PvPManager-Issues#101]
Hi there, 

My server has been having an odd issue where the entire server will time out when a player tries to escape combat by logging out. We have disabled combat tagging for the time being until this issue can be resolved. 

PvPManager version: v3.8
Server version: Paper 1.13.2 #544

If any further information is required, please don't hesitate to ask! 

Thank you, 
- David (Daph)

**Comment by NoChanceSD** [comment]
Doesn't seem to happen in my tests but post the error you get when it crashes please, maybe a conflict with other plugin. And check if v3.8.1 improved anything.

**Comment by Daphsquid** [comment]
I'll update it and reply back here after testing.

**Comment by Daphsquid** [comment]
This issue is fixed using the latest update. I'm not 100% sure on the cause of the server crash, but I suspect it was caused by NPC spawning when the player logs off (the Citizens plugin had to fix a crash issue with NPCs a few months back too). 

Regardless, since this is no longer an issue, I'll close this. I'll reply back if any other related issues occur. 

Thanks!
