### ISSUE TITLE
Server Crash on custom Jar - BeerSpigot

### ISSUE THREAD

**Issue by huntingzap** [NoChanceSD/PvPManager-Issues#102]
So the plugin works on 1.8 but when I switched my jar to Beerspigot, it stopped working and errors were made in my console, any help?

**Comment by NoChanceSD** [comment]
Don't think i will support that server jar but post the errors you get and PvPManager version and i will see what i can do.

**Comment by NoChanceSD** [comment]
Closed for inactivity. Reopen with more information if the issue still exists.
