### ISSUE TITLE
Spam in chat Spigot 1.13.2

### ISSUE THREAD

**Issue by Fiks75** [NoChanceSD/PvPManager-Issues#103]
Lots of chat spam message where pvp is disabled. Please fix it.
Много спама в чате, при входе в игру, где пвп отключен.

<a href="https://fastpic.ru/view/110/2019/0323/3cb0c499f5a229b1c51fd7d194ebe06c.jpg.html" target="_blank"><img src="https://i110.fastpic.ru/thumb/2019/0323/6c/3cb0c499f5a229b1c51fd7d194ebe06c.jpeg" border="0"></a>

Spigot 1.13.2
Worldguard-legacy-7.0.0-beta-03
Worldedit-bukkit-7.0.0-beta-05
PvPManager v3.8

**Comment by NoChanceSD** [comment]
Any errors in console? Can you translate that message to english for me? And please let me know what causes it to happen like if it is after the player just respawned.

**Comment by NoChanceSD** [comment]
Closed for inactivity. Reopen with more information if the issue still exists.
