### ISSUE TITLE
Error when using subside KOTH

### ISSUE THREAD

**Issue by MineTribes** [NoChanceSD/PvPManager-Issues#105]
Hey, when using your premium plugin with the Subside KOTH plugin I get this error:
https://pastebin.com/Wrgr3S9u

**Comment by NoChanceSD** [comment]
Is this still an issue? Seems like PvPManager might not be enabled yet, maybe that KOTH plugin didn't declare PvPManager as a dependency in plugin.yml and it enables before.

**Comment by NoChanceSD** [comment]
Closed for inactivity. Reopen with more information if the issue still exists.
