### ISSUE TITLE
How to connect the plugin to iDisguise?

### ISSUE THREAD

**Issue by Duioka** [NoChanceSD/PvPManager-Issues#111]
I put the plugin on turning into mobs iDisguis, this is the best plugin for this. Despite this plugin, it supports anything but this plugin. If I honestly would like the function "When PvP starts, some kind of command is registered in the config", this really is not enough. On my question: is it possible to somehow connect to iDisguis?

**Comment by NoChanceSD** [comment]
Do you mean disable disguises from iDisguise when entering combat? If that's what you want i can add it.
