### ISSUE TITLE
Disable glide when tagged

### ISSUE THREAD

**Issue by TonnyBear** [NoChanceSD/PvPManager-Issues#113]
Hello, I was wondering if you could insert one more disable option when tagged - GLIDE. 

Reason -  when in combat you can always boost yourself in the air with firework and glide your way out, its the same with trident and riptide enchantment when its raining. 
Thank you. 
http://prntscr.com/pn9vi4

**Comment by NoChanceSD** [comment]
Check version 3.8.8, i added a config option to block elytra gliding. 
Didn't look at riptide yet though, not even sure how it works tbh, haven't played much new versions but i will look into it.
