### ISSUE TITLE
Config per world

### ISSUE THREAD

**Issue by Norge100** [NoChanceSD/PvPManager-Issues#117]
So i have 2 world using Multiverse Core. It's Survival and UHC. I want force PVP enable in UHC and disable command.

**Comment by NoChanceSD** [comment]
In UHC negate this permission, depending on your permission plugin, do something like "-pvpmanager.pvpstatus.change" Should block /pvp command in that world. 
Then in UHC world execute the following command "/rg flag __global__ pvp allow" and it should force pvp on for all players.

**Comment by Norge100** [comment]
> In UHC negate this permission "pvpmanager.pvpstatus.change", depending on your permission plugin, it will be something like "-pvpmanager.pvpstatus.change" Should block the /pvp command in that world.
> Then also in UHC world execute the following command "/rg flag __global__ pvp allow" and it should force pvp on for all players.

Even if i type /rg flag __global__ pvp allow it should players can't still PvP if they disable in Survival World. In UHC World, i already fixed only 1 command and it's /event leave

**Comment by NoChanceSD** [comment]
If you have the setting "WorldGuard Overrides" in config set to true it should auto enable their pvp, even they disabled it before, just make sure there is a WorldGuard flag with PvP set to allow.  
And sorry, github formatting changed it, make sure it's \_\_global__ , not global

**Comment by Norge100** [comment]
> If you have the setting "WorldGuard Overrides" in config set to true it should auto enable their pvp, even they disabled it before, just make sure there is a WorldGuard flag with PvP set to allow.
> And sorry, github formatting changed it, make sure it's __global__ , not global

It's a command or config? If so, what's the command or config?

**Comment by NoChanceSD** [comment]
I'm assuming you have the WorldGuard plugin in your server, if you do, go into the UHC world ingame and execute the command "/rg flag \_\_global__ pvp allow" . Then, make sure you have the setting  "WorldGuard Overrides" set to true in PvPManager config.

**Comment by Norge100** [comment]
> I'm assuming you have the WorldGuard plugin in your server, if you do, go into the UHC world ingame and execute the command "/rg flag __global__ pvp allow" . Then, make sure you have the setting "WorldGuard Overrides" set to true in PvPManager config.

Ah, it's already enabled default on PvPManager config. I tested my alt account and my main account and it's working. Thank you
