### ISSUE TITLE
An internal error occured while attempting to perform this command

### ISSUE THREAD

**Issue by yukisho** [NoChanceSD/PvPManager-Issues#122]
**Describe the bug**
The only command that works is /pvpm

**To Reproduce**
Drop jar file into plugins directory and start server.

**Expected behavior**
It to work.

**Plugin and Server version**
3.10.0

**Screenshots**
Plugins list
https://i.imgur.com/87JkMCP.png

**Additional context**
Error in console when using /toggle
https://pastebin.com/caSNZFbG

**Comment by NoChanceSD** [comment]
I believe you're using craftbukkit, any reason to not be using spigot, or paper? It is a spigot plugin.
