### ISSUE TITLE
On 1.16 makes Citizens2 NPC's killable

### ISSUE THREAD

**Issue by sketrick** [NoChanceSD/PvPManager-Issues#124]
I'm able to kill NPC's if I run pvpmanager plugin.
Latest plugin build and latest spigot build.
https://ibb.co/gzrLsGR

**Comment by NoChanceSD** [comment]
Try the new 3.12 version and let me know if it's fixed.

**Comment by sketrick** [comment]
Now citizens npc don't load when I updated the plugin.
https://pastebin.com/uLCUgVDY

**Comment by sketrick** [comment]
Do you want to try my citizens save?

**Comment by sketrick** [comment]
Do you want to try my citizens save?

**Comment by NoChanceSD** [comment]
Should not be necessary, try version 3.12.1, I made a small mistake on the last update. Also, make sure to restart the server when you update the plugin in case you weren't.

**Comment by sketrick** [comment]
Works fine now. Thank you.
