### ISSUE TITLE
Factions v3.2.2 support

### ISSUE THREAD

**Issue by baticag** [NoChanceSD/PvPManager-Issues#125]
Output from console:
https://hastebin.com/iyimucivak.css

**Comment by NoChanceSD** [comment]
Sorry about that, there is a lot of Factions forks, try this update: https://www.spigotmc.org/resources/pvpmanager.10610/update?update=345083

**Comment by NoChanceSD** [comment]
I'm going to assume this is fixed and close it now. Let me know if not.
