### ISSUE TITLE
Combat Tag Bug

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#13]
Players who log out after being tagged log back in, except they seem to be teleported to some completely random location...

**Comment by NoChanceSD** [comment]
Well if they got killed then they will respawn in another place.

**Comment by LaughNgamez** [comment]
The problem is they're not being killed, they're still alive and log back in at some random area. Not even our official spawn.

**Comment by NoChanceSD** [comment]
Post your config if you can.
Also, do you use AuthMe and/or Essentials?

**Comment by LaughNgamez** [comment]
I use essentials, and here's my config:

http://pastebin.com/BMBZF0eS

**Comment by NoChanceSD** [comment]
Fixed
