### ISSUE TITLE
Error reading version number.

### ISSUE THREAD

**Issue by robert-harbison** [NoChanceSD/PvPManager-Issues#130]
I get this in my console when starting the server ```[18:17:16 ERROR]: Error reading version number! Comparing 7.0.4+f7ff984 to 7.0```

**To Reproduce**
Just install the plugin and run the server.

**Expected behavior**
To not have this error show in the console or if it is non important for it to be a warning instead of an error.

**Plugin and Server version**
PVPManager version: 3.13 (This is the premium version)
Paper version: git-Paper-246 (MC: 1.16.3) API Version 1.16.3-R0.1-SNAPSHOT.

**Additional context**
I am running Paper server.

**Comment by NoChanceSD** [comment]
Thank you for the report. That error happened because WorldGuard changed their version number with a "+" now instead of a "-", the plugin still works but WorldGuard support would be disabled. 
I uploaded a new update which should fix this, let me know in case it doesn't.
