### ISSUE TITLE
Chatcontrol Red incompatibility

### ISSUE THREAD

**Issue by JasmineWMCM** [NoChanceSD/PvPManager-Issues#135]
I can't do /pvp or any pvp commands with chatcontrol red.

**To Reproduce**
1. Go ingame
2. /pvp on/off
3. See no errors whatsoever

**Expected behavior**
I expected to be able to toggle.

**Plugin and Server version**
Use '/ver PvPManager' and '/ver' to get both versions

**Screenshots**
N/A

**Additional context**
When I removed Chatcontrol Red on my dev server it worked.

**Comment by NoChanceSD** [comment]
Seems like a problem with ChatControl or it's settings then. Not much I can do here since it works without it.
