### ISSUE TITLE
Combat tag friendly fire!

### ISSUE THREAD

**Issue by Fattix** [NoChanceSD/PvPManager-Issues#138]
**Describe the bug**
When two players are in the same faction, or are in a non pvp enabled area and they are both in combat tag they can hit eachother.

**To Reproduce**
1. Have you and another both hit a mob to get into combat tag
2. hit eachther

**Expected behavior**
It should have not allowed the two to hit eachother

**Plugin and Server version**
3.12.3

**Additional context**
This is not just a factions issue its all pvp disabled places this happens

**Comment by NoChanceSD** [comment]
Set vulnerable setting to false in the config.
