### ISSUE TITLE
Combat Tag does not recognize some commands

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#15]
Combat Tag block commands does not recognize commands from all plugins. Say there's a plugin such as Magicspells which players can define their own aliases to run commands/things PVPmanager does not block those commands.

A similar plugin Combat Tag does.

**Comment by NoChanceSD** [comment]
It blocks all commands except the ones in the whitelist, not sure what you mean.

**Comment by LaughNgamez** [comment]
It does not block certain kinds of commands from what I can see

**Comment by LaughNgamez** [comment]
For example a plugin such as Magicspells: http://pastebin.com/c32ERW9H
Creates custom commands that are not official bukkit commands. These appear to not be blocked.

**Comment by NoChanceSD** [comment]
Maybe because it's being executed on console?
In that config you showed me, if you try setting "execute-on-console-instead: false" does it work?

**Comment by LaughNgamez** [comment]
That's just an example, and Combat Tag manages to block unofficial commands like this. Adding support to do this would be greatly appreciated.

**Comment by NoChanceSD** [comment]
I have no idea what you mean, in my server it blocks all commands, doesn't matter if they exist or not.
If i type /safkds it blocks it anyway unless whitelisted.
