### ISSUE TITLE
Reset state option

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#16]
A while back NoChance in PM said he made a ticket for resetting a players PvP toggle status when switching worlds.

This was when I was inquiring about being able to disable pvptoggle in a world by disabling a permission the toggle permission. Unfortunately a player with PvP disabled in one world could go to another and still have pvp disabled.

Ideally there'd be an option in the config to make it so when a player switches world their pvp status is set to default.

**Comment by NoChanceSD** [comment]
Let's move the discussion here: https://github.com/NoChanceSD/PvPManager/issues/82

**Comment by NoChanceSD** [comment]
Added in latest update.
