### ISSUE TITLE
Combat Tag not blocking commands

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#17]
So I made an issue report before but did a horrible job explaining it.
The issue is Tagging a player does not block some commands which from what I know use a different detection method.

When running a normal command when tagged such as "/warp" it simply blocks the command.
![canttp](https://cloud.githubusercontent.com/assets/12781929/11580478/a39a78f4-99ec-11e5-8beb-eac3802468e2.png)

However some plugins such as MagicSpells or Mycommand allow the user to create custom commands. For an example here I created a command which runs "warp smelt" when a user runs "/smelt" any "configured" commands by plugins like this are not blocked.
http://pastebin.com/veLTfR8x

For example when running this command after being tagged it still executes fine because the Tag system does not recognize the "/smelt" as a command. A similar plugin called "Combat tag" blocks these customized aliases fine.

![cantp](https://cloud.githubusercontent.com/assets/12781929/11580541/322689d2-99ed-11e5-84d5-a12e4ee9caea.png)

**Comment by NoChanceSD** [comment]
Thank you for the detail. Now i understand what you meant =P
I think i can fix it quite easily.

**Comment by NoChanceSD** [comment]
It should not be a problem anymore on the latest free version build.
It will get included in next premium update as well.

**Comment by LaughNgamez** [comment]
Thanks a bundle, also sorry for the horrible explanation before.
Looking forward to the next premium build and thanks for all the plugin support.

**Comment by NoChanceSD** [comment]
Let me know if it got solved in the update
