### ISSUE TITLE
Item drop if killed bij fire damage

### ISSUE THREAD

**Issue by MonkvanNederland** [NoChanceSD/PvPManager-Issues#2]
Hi, first of all i want you to know the plugin is awesome!

Here is the issue;
"Item Drop" is set on 'Keep' in the config and it works very wel, but sometimes there is a glitch that items do drop from players when the are killed with a Fire Aspect sword or with a Flame bow.

Monk

**Comment by NoChanceSD** [comment]
Thank you for your report. 
It's probably because minecraft fails to detect what player placed him on fire and PvPManager doesn't count it as PvP. I will try to figure out some solution.

**Comment by NoChanceSD** [comment]
When this happens, can you tell me what do the death messages say?

**Comment by MonkvanNederland** [comment]
There was no death message from PvPManager.
Good news! Items no longer drop when players are killed by a Fire Aspect Sword or Flame Bow. You fixed it!
Strange part was that items from OP's still dropped after being killed bij fire damage, and when an OP killed a player there was no custom death message, only if the OP jump-hitted the player xD However, this was magically solved after one hour or so without a restart. So yeah, no more problems!
I will update our gamemodes with the new update. Thank you very much for the quick reply and fixing the issue on such short notice! Great support!

**Comment by NoChanceSD** [comment]
Alright, let me know if there are more issues.
