### ISSUE TITLE
Force PvP Message

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#20]
Force PvP default when switching worlds is really useful but it would be nice if the message only played when a users status is actually changed.

For example user with PvP off enters a world with pvp enabled: It would say "PvP enabled"
Now a user with PvP on enters a world with pvp enabled: There would be no message.

**Comment by NoChanceSD** [comment]
I agree with you, will be in next update.

**Comment by NoChanceSD** [comment]
Added in 3.3.9
