### ISSUE TITLE
Border Hopping won't work

### ISSUE THREAD

**Issue by MithrandirCraft** [NoChanceSD/PvPManager-Issues#22]
PvPManager version: 3.3.5.3
Spigot: 1.8.8

-------------------------------
Relevant configuration:

  Gerneral:
    Stop Border Hopping: true

-------------------------------

The border hopping function isn't working when set to true. 
Players are still inmune to pvp when tagged on both Factions safe zones and WorldGuard pvp off flagged areas.
This started happening suddenly, but I don't know on which build, all I can say is that it still happens.

**Comment by NoChanceSD** [comment]
Which version of WorldGuard?

**Comment by MithrandirCraft** [comment]
@NoChanceSD 6.1

**Comment by NoChanceSD** [comment]
I really don't have this issue on my test server, are both players tagged when inside the regions?

**Comment by MithrandirCraft** [comment]
Yes. I am going to test this localhost. This definetly doesn't work on my server, try it yourself:

sv1.mithrandircraft.es

**Comment by MithrandirCraft** [comment]
... I'm sorry, but I can still reproduce this on my localhost server.

I must say, my localhost server is similar in some ways to my main server, I tried it in similar conditions, so I don't know what else could be intervening exactly.

All I know is that the "Hey! Sorry but you can't PvP here" message is being triggered every time I try to hit a tagged player by me, inside a non PvP WorldGuard area (PvP starts outside the area, and I attempt to keep hitting the other player inside, without success), and I also know that this issue persists when the area is a Faction safezone, so basically players are being protected when they shouldn't.

I can reproduce this issue on both my Main, and test servers (My test server has fewer plugins that could be intervening in this).

So I would bet I either have something configured wrong on both my servers, or there's something not right somewhere.

**Comment by NoChanceSD** [comment]
It seems one of your plugins is conflicting, if you find out which one it is let me know.

**Comment by MithrandirCraft** [comment]
I'm going to keep testing this e_e' I will test it on a blank localhost server.

**Comment by NoChanceSD** [comment]
This is pretty much the last issue i wanted to solve before releasing a new update xD
I will keep trying but so far it has been working.

**Comment by MithrandirCraft** [comment]
I'm using WorldEdit, WorldGuard & PvPManager on their own, on a Blank Spigot Server.

Tagging isn't working for some reason (wtf), so I can't even test the main bug :/

Was there some dependency to PvPmanager that I'm forgetting or something?

**Comment by NoChanceSD** [comment]
What error are you getting?

**Comment by MithrandirCraft** [comment]
Vault not found? Well I'll try that.

**Comment by MithrandirCraft** [comment]
Video showcasing the issue: https://youtu.be/zuyPW8Y6leE

I'm just using the default pvpmanager config from the latest version on a spigot server with the conditions you can see for yourself. And the issue still persists :S, what the hell am I doing wrong?

**Comment by NoChanceSD** [comment]
You don't seem to be tagged... like i said above, both players need to be tagged.

**Comment by MithrandirCraft** [comment]
You are right. That's the issue, I can't hit players as an admin because I somehow don't get tagged.
I could before though. In any case, it's enough for me if it works like this :)

**Comment by NoChanceSD** [comment]
To get tagged you need to not be OP or negate the permission "pvpmanager.nocombat"

**Comment by MithrandirCraft** [comment]
Hey, thanks a lot for your help :)
