### ISSUE TITLE
Not compatible with popular plugin Featherboard

### ISSUE THREAD

**Issue by SugarRealms** [NoChanceSD/PvPManager-Issues#24]
Several features seem to break when using the plugin "Featherboard."  Such as the nametag feature and the no safezone feature.

**Comment by NoChanceSD** [comment]
Have you confirmed it only happens when using featherboard?

**Comment by NoChanceSD** [comment]
Check if v3.3.9 fixes this issue please

**Comment by NoChanceSD** [comment]
Closing
