### ISSUE TITLE
Method to disable a message

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#25]
Editing messages is nice but from what I know there is currently no way to disable one from playing. For example if you want to disable the tag message all you can do is delete it which makes it run a blank line with no text. It would be nice if deleting a message entirely made no line run.

**Comment by NoChanceSD** [comment]
In next update, all (or most of them) messages will just not show if you delete them in messages file.

**Comment by NoChanceSD** [comment]
Added in v3.3.9
