### ISSUE TITLE
Not compatible with citizens

### ISSUE THREAD

**Issue by SugarRealms** [NoChanceSD/PvPManager-Issues#30]
http://pastebin.com/Z6WuWFB9 Not compatible with citizens. Just make it so if a player contains space in its name then it isn't combat logged. Trust me, I've had this issue with many plugins and that's the only way due to the fact that citizens tells plugins that it's a real human.

**Comment by NoChanceSD** [comment]
Not sure, is this fixed?

**Comment by NoChanceSD** [comment]
Closing for no reply.
