### ISSUE TITLE
Option to disable certain protections with pvp toggle

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#33]
It would be nice if there was an option to be able to disable protections from things like players using lava buckets or lighters around pvp toggled users.

**Comment by NoChanceSD** [comment]
Is this that important, i'm thinking about not adding it...

**Comment by LaughNgamez** [comment]
This would be nice to be added. Not being able to use a lighter or lava bucket near friends can be a nuisance.

**Comment by NoChanceSD** [comment]
If they are near friends maybe he could have pvp enabled?

**Comment by LaughNgamez** [comment]
Then they could be ambushed. Honestly, I'd rather have the area protection removed completely if there is no option to disable it.

**Comment by NoChanceSD** [comment]
Fine, i will add it.

**Comment by LaughNgamez** [comment]
It's appreciated.

**Comment by NoChanceSD** [comment]
Added on new update.
