### ISSUE TITLE
[Suggestion] Permission to disable drops on death

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#35]
I notice it's possible to disable users drops on death, however I want to disable them just for some users. It would be nice if there was a permission or easy way of controlling whether a user drops items on death.

Hopefully this can be added soon so another pvp plugin doesn't need to be added.

**Comment by tuanjr** [comment]
Add this, please, asap.
and fix bug with player's armour

**Comment by NoChanceSD** [comment]
Decided not to add this. Some plugin managing player drops should do it, sorry for dragging this so long.
