### ISSUE TITLE
Requests / Offer

### ISSUE THREAD

**Issue by thebraino** [NoChanceSD/PvPManager-Issues#37]
Hello, I recently installed your free plugin on a small-ish 1.7.10 server, and I'm loving it!
There were two things I'm still looking for:

1: CommandOnTag - the main mod we use has a separate teleport using a GUI so we're unable to block players from using it during a fight; however, if we could issue commands on tag (like your other events), the mod would allow us to set the cooldown time before teleporting (using different handles for player1 and player2).

2: /hunt (since /tag is implemented) - we have a problem of players seeing someone approaching, and log out before becoming tagged. I would really love if players could issue a command to initiate combat at a player within a range, and I could just increase your variable for cooldown time to be considered out-of-combat to compensate.

I understand your rights as the plugin writer, and would love to discuss paying for the premium version plus what you deem fair for these two implementations.

Thank you so much for the free version!

**Comment by NoChanceSD** [comment]
For number 1, by enabling the option that blocks all teleports should block this as well.
Number 2, i don't think it's something i want to add for now, sorry.
