### ISSUE TITLE
Lag (I know... worst title ever)

### ISSUE THREAD

**Issue by mickcoyne** [NoChanceSD/PvPManager-Issues#38]
This is the timings from my server. This is when their is lag on my server. This is causing more of a drain than slimefun program. If you could please fix this, I'm very willing to buy premium for a fix

`PvPManager v3.0-SNAPSHOT-b190Total: 60.457 s Pct: 0.50%

   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event

       0.50%	120,455.23%	 60.23 s	60,227.62 ms	 0.0	       0.0k	    Task: ConfigManager$1(interval 360000)

       0.00%	   0.00%	  0.10 s	     0.00 ms	 0.2	      49.4k	    PlayerListener::onPlayerInteract(PlayerInteractEvent)

       0.00%	   0.00%	  0.05 s	     0.00 ms	 0.1	      22.2k	    EntityListener::onPlayerDamage(EntityDamageByEntityEvent)

       0.00%	   0.00%	  0.03 s	     0.00 ms	 0.1	      22.2k	    EntityListener::onPlayerDamageOverride(EntityDamageByEntityEvent)

       0.00%	   0.00%	  0.02 s	     0.00 ms	 0.1	      22.2k	    EntityListener::onPlayerDamageMonitor(EntityDamageByEntityEvent)

       0.00%	   0.00%	  0.02 s	     0.00 ms	 0.1	      13.6k	    PlayerListener::onPlayerPickup(PlayerPickupItemEvent)

       0.00%	   0.00%	  0.01 s	     0.00 ms	 0.0	       3.3k	    PlayerListener::onBlockPlace(BlockPlaceEvent)

       0.00%	   0.22%	  0.00 s	     0.11 ms	 0.0	       0.0k	    PlayerListener::onPlayerJoin(PlayerJoinEvent)

       0.00%	   0.01%	  0.00 s	     0.00 ms	 0.0	       0.8k	    PlayerListener::onPlayerTeleport(PlayerTeleportEvent)

       0.00%	   0.01%	  0.00 s	     0.00 ms	 0.0	       0.5k	    PlayerListener::onCommand(PlayerCommandPreprocessEvent)

       0.00%	   0.08%	  0.00 s	     0.04 ms	 0.0	       0.0k	    PlayerListener::onPlayerLogout(PlayerQuitEvent)

       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.1k	    Task: CleanKillersTask(interval 3000)

       0.00%	   1.27%	  0.00 s	     0.63 ms	 0.0	       0.0k	    PlayerListener::onPlayerDeath(PlayerDeathEvent)

       0.00%	   0.04%	  0.00 s	     0.02 ms	 0.0	       0.0k	    PlayerListener::onChangeWorld(PlayerChangedWorldEvent)

       0.00%	   0.11%	  0.00 s	     0.06 ms	 0.0	       0.0k	    PlayerListener::onPlayerRespawn(PlayerRespawnEvent)

       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.0k	    PlayerListener::onPlayerKick(PlayerKickEvent)
`

**Comment by NoChanceSD** [comment]
Just disable checking for updates in config, should fix it.
