### ISSUE TITLE
Pluign throws error upon player join with mc 1.8.8

### ISSUE THREAD

**Issue by MinecraftB0ss** [NoChanceSD/PvPManager-Issues#39]
Get this error when players join in, only happens with premium version.

http://pastebin.com/W33BtsiX

**Comment by NoChanceSD** [comment]
You are not using the latest version. Should be fixed.

**Comment by MinecraftB0ss** [comment]
on latest: http://pastebin.com/QPJBFTBJ

**Comment by NoChanceSD** [comment]
Does this still happen?

**Comment by MinecraftB0ss** [comment]
yes, issue hasent been fixed

**Comment by NoChanceSD** [comment]
Can you try deleting your users.yml file? It might solve it.

**Comment by MinecraftB0ss** [comment]
you havent updated the plugin, how would it have fixed itself?

**Comment by NoChanceSD** [comment]
Yea, i noticed my mistake after i asked if it still happens.
But anyway, can you try deleting your users.yml file? Or see if it's corrupt somehow.

**Comment by NoChanceSD** [comment]
This should be fixed, let me know if not.
