### ISSUE TITLE
Method to disable NPCs for some users

### ISSUE THREAD

**Issue by LaughNgamez** [NoChanceSD/PvPManager-Issues#41]
A good option for PvPManager would be the option to disable NPCs by giving a permission to a user.

This would be a good addition due to the fact that there are some situations in which a user needs to be able to be tagged in PvP so they cant do commands/teleport but in which you don't want their NCP to spawn and drop items.

My personal need for this request is due to the fact that we use a custom drops system. However when a user combat logs the NPC drops their normal items. Hopefully with something like a permission such as pvpmanager.noNPC this could be achieved.

**Comment by LaughNgamez** [comment]
Really hoping for this and my other suggestion to be added. As currently there are some users that I don't want to give drops but still be able to be tagged. This is because I want them to not be able to use commands in PvP but not spawn an NPC as those give drops.

**Comment by NoChanceSD** [comment]
Added this for next update. Permission is "pvpmanager.noSpawnNPC"
