### ISSUE TITLE
kill arrow bug.

### ISSUE THREAD

**Issue by andris155** [NoChanceSD/PvPManager-Issues#42]
If I kill myself with a bow and arrow on my SkyPvP server, it counts as a kill, meaning that I can get infinite amount of kills just by killing myself.

**Comment by NoChanceSD** [comment]
It counts as a kill for which plugin? If it is for your skywars plugin then it's not pvpmanager fault,

**Comment by andris155** [comment]
I sorry, scoreboardstats bug...
