### ISSUE TITLE
Enchanted Bow (Flamme).

### ISSUE THREAD

**Issue by dadee971** [NoChanceSD/PvPManager-Issues#47]
Hi,
I have a big problem with this plugin that i've bought.
When the pvp is off, players can still kill each others with a bow with flamme enchant.
They don't take damage from the bow but only from the fire ticks.
I'm oblige to disable fire damage with Worldguard until this bug will be solved.

PvPManager [Paid] 3.5.8.3

CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT) You are running the latest version

**Comment by andris155** [comment]
same problem

**Comment by BlackBeltPanda** [comment]
Same with me on Paper 1.10.2 using PvPManager 3.0.

**Comment by CeIebrimbor** [comment]
Its a new event in 1.10.2 that deals with firearrows. Had same issue on GriefPrevention until author fixed.

**Comment by NoChanceSD** [comment]
Should be fixed
