### ISSUE TITLE
Task #41072 for PvPManager v3.3.2 generated an exception

### ISSUE THREAD

**Issue by andris155** [NoChanceSD/PvPManager-Issues#5]
http://pastebin.com/zXvNsnR4

**Comment by NoChanceSD** [comment]
Thank you for the report.
Can you tell me which version of (Paper)Spigot are you using or post the output of the /ver command.

**Comment by andris155** [comment]
This server is running CraftBukkit version git-PaperSpigot-5be55c3-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by NoChanceSD** [comment]
Will be fixed in next update
