### ISSUE TITLE
Dupe items with Npc option

### ISSUE THREAD

**Issue by KikiCro26** [NoChanceSD/PvPManager-Issues#51]
Dupe Items with npc option 
player can join back on server when there npc is online 
after that they throw items to npc go back to hub and come back and he have double items 
I have try to disable Npc but not work in config I use 1.10 version

**Comment by CeIebrimbor** [comment]
Lucky you got NPC's to even work... NPCs (basically half of the main features) are broken in 1.10.

**Comment by NoChanceSD** [comment]
You still have this issue? I can't replicate it currently.

**Comment by CeIebrimbor** [comment]
I've never seen this.
