### ISSUE TITLE
Bug with safe zones.

### ISSUE THREAD

**Issue by Jozznak** [NoChanceSD/PvPManager-Issues#55]
Hi, I would suggest a little change on the method that prevent users scape form pvp using safe zones.

Push buck gets bug and players jump everywhere while the plug tries to push back the player from the region. So I would suggest instead of that,  one that creates like a glass wall in front of the player where the safe zone starts so he cannot pass through.

Another thing that would be awesome if that when players use a invisible potion, the tag should disappear too to let the potion works fine, if not, other players can see invisible payers that are tagged.

Regards, 
Nacho.

**Comment by NoChanceSD** [comment]
Yes, the glass wall is a good suggestion which is my plans for some day. However, i can't tell you when i will add it but probably not soon. 
About the tag being visible, this is a minecraft issue with teams, can't do much about it unfortunately.
