### ISSUE TITLE
Newbie_Protection_Atacker Message Issue

### ISSUE THREAD

**Issue by CeIebrimbor** [NoChanceSD/PvPManager-Issues#58]
Newbie_Protection_Atacker
(this is spelling by default)

Is this misspelled item possibly causing it not to be called correctly? I've had players say they attack someone and they are invincible for "no reason". I could only assume it was Newbie protection and they didn't get a message. Could this misspelled event in messages.properties be a possible cause?

Thank you!

**Comment by NoChanceSD** [comment]
It's not misspelled afaik, it's the message a player receives when attacking someone with newbie protection enabled. I'm not sure why they are invincible though, i believe i send a message whenever pvpmanager blocks an attack except for respawn protection.

**Comment by CeIebrimbor** [comment]
PVPMAN Default= **Atacker**
Correct= **Attacker**

Newbie_Protection_Atacker (wrong)
vs.
Newbie_Protection_Attacker (correct)

**Comment by NoChanceSD** [comment]
Oh didn't even notice that typo, that is possible yes. I will check that when i get some free time.

**Comment by NoChanceSD** [comment]
Alright, so i checked that and the typo isn't affecting it. The only block of damage where i don't send a message is respawn protection, could it be that? Should only last a few seconds though depending on your config.

**Comment by CeIebrimbor** [comment]
Very well. As I said, it was only reported and a player trying to kill a newjoin was confused. my server has an environment where newjoin hunting is very rare, so I didn't have much to go off and the typo seemed to be too coincidental that I thought I would bring it up.

Thank you for checking.
