### ISSUE TITLE
God Mode Fire Arrow

### ISSUE THREAD

**Issue by JingoMCS** [NoChanceSD/PvPManager-Issues#60]
Is it possible to disable god mode if a player in essentials god mode uses a bow with fire arrow? For now, they stay in god mode and the player who gets hit is damaged by the fire. Thanks

**Comment by NoChanceSD** [comment]
And why is the player being attacked only get damaged by fire? Shouldn't fire also be blocked by the plugin which blocked the arrow attack?

**Comment by NoChanceSD** [comment]
This is fixed long ago so i'm closing.
