### ISSUE TITLE
Disable collision option [FEATURE]

### ISSUE THREAD

**Issue by maxlehot1234** [NoChanceSD/PvPManager-Issues#61]
Hi, are you able to add something to prevent collision. I have a plugin like this on my server but your plugin have priority on it...

It can be really, really cool if you can add an option in the config to disable this feature.

Thanks again

**Comment by CeIebrimbor** [comment]
What do you mean? Player collisions? That is impossible for a plugin without creating a Scoreboard Team with **every** player on the same team with collisions off.

**Comment by maxlehot1234** [comment]
I have the nocollision plugin, but your plugin re-enable the collision between players in all worlds, all regions, EVERYWHERE...

So the nocollision plugin was not necessary on my server, which is veryyy badd.

This is the plugin: https://www.spigotmc.org/resources/no-collision-with-patch.26347/

**Comment by CeIebrimbor** [comment]
Those plugins require Scoreboard teams. You have something messing with scoreboard teams most likely. 

@NoChanceSD 
PvP manager touch scoreboard?

**Comment by maxlehot1234** [comment]
Directly when I put pvpmanager on my server collisions are enabled again.... So something "fuc****" with collision ...

**Comment by maxlehot1234** [comment]
It was fix with latest nocollision plugin version that include a patch for spigot.

**Comment by NoChanceSD** [comment]
@CeIebrimbor 
Yes, it uses teams to color player nametags but this is fixed anyway so no problem.

**Comment by CeIebrimbor** [comment]
PaperSpigot (and many plugins used to accomplish nocollide). They make a permanent team to place players on, how does PvPM do it? Would it clash with player's teams?
