### ISSUE TITLE
Add an option in the config to kill players instead of spawning NPC if they log in a no-pvp zone

### ISSUE THREAD

**Issue by ghost** [NoChanceSD/PvPManager-Issues#64]
NPCs don't spawn inside no-pvp zones and even if they did, they can not be killed so can you implement an option to kill the player if he logs in a no-pvp zone?

**Comment by NoChanceSD** [comment]
Sorry for such a late answer. They don't spawn in no-pvp zones according to the config option "No Spawn In WorldGuard: true" but i agree that it's not a good method to solve the issue. I will make the NPC vulnerable to PvP.
