### ISSUE TITLE
Border hopping loggers invincible

### ISSUE THREAD

**Issue by CeIebrimbor** [NoChanceSD/PvPManager-Issues#66]
The anti-border hopping cooldown before a player is protected is fine, but if they combat log in the "safe zone", the NPC spawned will gain the invincibility of the safe zone. Thus bypassing the threat of being killed when the NPC is spawned.

**Comment by CeIebrimbor** [comment]
Similar to #64, but NPCs do spawn in my safe zone. They are just invincible.

(I use Grief Prevention)

**Comment by NoChanceSD** [comment]
I apologize for answering only now, i will make the NPC be vulnerable everywhere like i also said in #64.
As you said, it doesn't make sense for the NPC to be invulnerable.

**Comment by NoChanceSD** [comment]
Should be working correctly in latest update.
