### ISSUE TITLE
Hey im having this trouble !

### ISSUE THREAD

**Issue by xXPavoXx** [NoChanceSD/PvPManager-Issues#68]
29.01 12:25:41 [Server] ERROR Could not pass event PlayerDeathEvent to PvPManager v3.6.4
29.01 12:25:41 [Server] INFO org.bukkit.event.EventException
29.01 12:25:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
29.01 12:25:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
29.01 12:25:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
29.01 12:25:41 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
29.01 12:25:41 [Server] INFO at nc.bf.a(SourceFile:125) ~[?:?]

**Comment by NoChanceSD** [comment]
That means you configured 'Extra Drops' wrong in config file.
- 1,DIAMOND 
Would drop 1 diamond on death, you probably have only one word there.
