### ISSUE TITLE
pvptag off

### ISSUE THREAD

**Issue by Johandrex** [NoChanceSD/PvPManager-Issues#69]
I have turned on "Vulnerable: true" in the "Anti Border Hopping" section. I'm however having an issue with players fighting in the spawn area. It'd be very useful if you could add a command that disables pvp for a specific user with "/pvptag [player] off". If that can't be added I'd be glad if you could add zone exclusions beneath the Anti Border Hopping section instead. Would be very useful. 

  Zone Exclusions:
    - world:spawn_area

**Comment by NoChanceSD** [comment]
Doesn't the /pvp command already work for that?

**Comment by Johandrex** [comment]
It disables the pvp for the player completely, I'm only interested in disabling the players current tag so he's unable to attack/be attacked in a specific zone.

**Comment by NoChanceSD** [comment]
Basically, you want certain regions where the vulnerable option shouldn't work?

**Comment by NoChanceSD** [comment]
See if latest update does what you needed.

**Comment by Johandrex** [comment]
Very useful, thank you very much.
