### ISSUE TITLE
Koth and PvPManager

### ISSUE THREAD

**Issue by SnakeDaoust1232** [NoChanceSD/PvPManager-Issues#70]
Hello,

I have a KOTH plugin installed on my factions server and i have an issue that needs to be resolved ASAP. Kids that are on noobie protection are capping koth for free since they cant be hit off the koth. Can you make it so that the plugin has KOTH support? I need to to either deny them from being able to cap or when they enter the koth region it disables their noobie protection.

Here is the KOTH plugin i use, im pretty sure they API is really easy.

Plugin: https://www.spigotmc.org/resources/koth-king-of-the-hill-mc-1-7-to-1-11.7689/
API: http://dev.thomasvdbulk.nl/KoTH/javadocs/

Regards,
Jacob Daoust

**Comment by NoChanceSD** [comment]
Fixed afaik.
