### ISSUE TITLE
Plugin didn't work + Player Drop Mode bug

### ISSUE THREAD

**Issue by kevintong139** [NoChanceSD/PvPManager-Issues#71]
My server's version is 1.11.2
If I try to use PvPManager ver 3.7.4, plugin didn't work
If I use ver 3.7, Player Drop Mode didn't work
Edit: just forgot that you can use lava bucket on PvP protected player in ver 3.7
Edit 2: tried out v3.6.4 on my server, it all worked expect Player Drop Mode

**Comment by NoChanceSD** [comment]
Any error at all in 3.7.4?
If nothing works as you say there must be some error when the server is starting and loading pvpmanager.
