### ISSUE TITLE
/pvp isn't working 

### ISSUE THREAD

**Issue by PurelyAliyah** [NoChanceSD/PvPManager-Issues#72]
Users aren't able to use /pvp on my server :(

I should probably mention that it's not Permissions I've already tried I've been using this for awhile and it just stopped working. I don't have any errors in the console.

I've literally tried everything and I mentioned this in the spigot discussions hoping to mention it here to hopefully get a fix for it.

**Comment by NoChanceSD** [comment]
Hello, isn't there any error in console when you try to use the command?
Also no message at all? If there is nothing at all, the plugin may have failed to load, check your server log for errors.

**Comment by PurelyAliyah** [comment]
There isn't a console Error when players do /pvp but if I do /pm reload there is. 

https://pastebin.com/40QyEVLS

This is the only error I'm getting, I'm able to do /pvp even when I'm not opped, but no one else is.

**Comment by NoChanceSD** [comment]
Try latest version, let me know if it fixes it issue please.
