### ISSUE TITLE
Drop Mode not working

### ISSUE THREAD

**Issue by ghost** [NoChanceSD/PvPManager-Issues#73]
I contacted you about this issue on the spigot forums a while ago but there was nothing forthcoming, it just isn't working. I don't have any other plugins that affect keep inventory status really, other than the normal game rules of the server, though I would assume that this plugin would override that. 

So what can I do, if its debugging or showing logs or anything, to help debug this problem?

**Comment by NoChanceSD** [comment]
No, if you have the gamerule keepinventoy on then that overrides the plugin if i remember correctly.
If you don't, then make sure there are no error at all in your logs and maybe provide your plugin list so i can check it out.

**Comment by MrHumblePie** [comment]
Thanks for the reply. My keepinventory gamerule is set to off, so when players die their items drop. I thought having KEEP mod on in the pvp plugin would overrule that but it doesn't seem to. My logs show no issues with the plugin but I will double check this when I restart the server this afternoon. 

Meanwhile my plugin list can be viewed here https://minecraft-statistic.net/en/server/37.59.144.213_25565/statistics/ (scroll down)

**Comment by MrHumblePie** [comment]
Yeah all i get from the start up log is
04.04 14:18:12 [Server] INFO [PvPManager] Enabling PvPManager v3.7.4.2
04.04 14:18:12 [Server] INFO [PvPManager] Vault Found! Using it for currency related features
04.04 14:18:12 [Server] INFO [PvPManager] WorldGuard Found! Enabling WorldGuard Support
04.04 14:18:12 [Server] INFO [PvPManager] NPCs are supported in this version!
04.04 14:18:12 [Server] INFO [PvPManager] Auto Respawn is supported in this version!

Also nothing comes up on console when a player kills another player
