### ISSUE TITLE
Not tagged after logout

### ISSUE THREAD

**Issue by grzegorzekkk** [NoChanceSD/PvPManager-Issues#74]
Hello, I have one problem with pvpmanager
When player is tagged and logs out, he is killed (set in config) but when he returns to server and fights again, he is not tagged again.
Only after reload of plugin he is able to be tagged again.
Here is my config: https://pastebin.com/c3NpcSeQ
Thanks!

**Comment by NoChanceSD** [comment]
Couldn't reproduce in current version.
