### ISSUE TITLE
suiciding before death

### ISSUE THREAD

**Issue by MithrandirCraft** [NoChanceSD/PvPManager-Issues#76]
PvpManager v 3.7.4
Spigot for MC 1.11.2

People are using /suicide on my server in order to avoid actually getting killed by another player (Not extremely bad, but can still affect scores. Faction power still goes down though...). How can I stop this without denying all commands during pvp? Something like a specific command blacklist would do the trick.

**Comment by NoChanceSD** [comment]
There is an option for command blacklisting while tagged in combat.
