### ISSUE TITLE
API

### ISSUE THREAD

**Issue by xtomyserrax** [NoChanceSD/PvPManager-Issues#77]
Hey, could you help me a little bit with your API? I dont understand it very well, could you give me an example code to set some things when a player is tagged and untagged from pvp?

Thanks!

**Comment by ChimpGamer** [comment]
I have an issue with the API. 
`    //Internal
    private static PlayerHandler getPlayerHandler() {
        PvPManager plugin = (PvPManager) Bukkit.getPluginManager().getPlugin("PvPManager");
        return plugin.getPlayerHandler();
    }`

When I hove with my mouse over PlayerHandler it says: Can't resolve symbol 'PlayerHandler'.
Everything else is fine so far.

**Comment by xtomyserrax** [comment]
Bump

**Comment by NoChanceSD** [comment]
Hi, sorry for taking so long. If you're still interested, the answer was basically 
`Player p;
PvPlayer player = PvPlayer.get(p);
p.isInCombat();`
Currently there are no events for tag/untag but that might change.
