### ISSUE TITLE
PvP in Safezone

### ISSUE THREAD

**Issue by Nico180902** [NoChanceSD/PvPManager-Issues#78]
Dear Developer,
I have a problem with PvP in Savezones. I want that players can also get hurt in a Safezone if they are in combat. But my problem is that if I hurt a player and he runs into the savezone, I can't hit him anymore. The WorldGuard PvP flag in the Safzone is "deny", if I set it to "none" or "allow" you van instantly hit all the players, so this option doesn't save the problem. In the plugin config I set Vuneranle and WorldGuard Overrides to "true". What can I do to solve my problem?
Game Version 1.11.2, Plugin Version 3.4.7.2, Config Version 51
UPDATE: I can't hit the player in safezone while combat because my account with the right of Operator doesn't get tagged when he gets hit. Why is that so?

**Comment by NoChanceSD** [comment]
You most likely don't care anymore because it has been so long but in case you do or anyone else has this question, it is because there is a permission "pvpmanager.nocombat" which all operators have by default. You can negate this permission in your permission plugin to get tagged.
