### ISSUE TITLE
Player Permanent Red name

### ISSUE THREAD

**Issue by bartonsweb** [NoChanceSD/PvPManager-Issues#8]
After purchasing and installing the plugin, it's been working perfectly however there is one specific player on the server than has a red name permanently, he's not in combat as he can tp, log out, etc perfectly fine. I've tried disabling PVP on him and enabling it again with no success. Server restart also did not help.

Even NPCs created via citizen with his name have a red nametag... This hasn't happened to any other player. I am at a loss, Is this a plugin bug or is there something causing this? Any ideas?

I've attached my config file so you can see my setup (Mostly default).

[config.txt](https://github.com/NoChanceSD/PvPManager-Issues/files/36940/config.txt)

**Comment by bartonsweb** [comment]
Okay it started out with just one player but it seems that it is happening to more and more players - regardless of pvp tag, server restarts etc they all keep the name colour permanently as if they're still in pvp.

**Comment by bartonsweb** [comment]
It was fixed, but fixing required enabling tag colours for a while, then disabling them again. That refreshed all player name colours. So far no player has been stuck with a permanent colour since that. I will update/reopen if it occurs again but so far it looks okay.

**Comment by bartonsweb** [comment]
Looks like a few hours later and another player has a permanent red name. I know that enabling and disabling the pvp toggle nametags will reset the name colours but obviously doing that constantly isn't a solution. Really weird issue to be honest, hope you can help :)

**Comment by NoChanceSD** [comment]
I believe i already have a fix ready but just to make sure, has you server crashed recently?

**Comment by bartonsweb** [comment]
Nope no crashes recently

**Comment by NoChanceSD** [comment]
Should be fixed in latest update, please let me know.

**Comment by bartonsweb** [comment]
Have updated and reset all players by enabling and disabling PVP toggle name colours. Unfortunately this doesn't seem to be fixed for us yet :(

**Comment by NoChanceSD** [comment]
Should be fixed for good now.

**Comment by NoChanceSD** [comment]
Closing as it seems fixed
