### ISSUE TITLE
Spawn PVP Issue

### ISSUE THREAD

**Issue by DarnItDan** [NoChanceSD/PvPManager-Issues#86]
Hello. My name is DarnItDan and I'm a Project Manager on Kronic Zombie Survival. We have had this bug for a while with PVPManager+ where if you tag someone in a PVP zone and they run into a PVP zone, only certain things with hurt the player. Here's a video explaining it further. 
https://youtu.be/Hr4VIPRwki8
Thank you.

**Comment by NoChanceSD** [comment]
It's been a while and the video is unavailable, let me know if it's still an issue.
