### ISSUE TITLE
Combat tag not working properly

### ISSUE THREAD

**Issue by LeDadSnatcher** [NoChanceSD/PvPManager-Issues#9]
For a few days I have been getting a problem with the combat tag system. Sometimes when someone is hit, there combat tag will not get removed after the 15 second timer that I had set. This means that they cannot do any commands unless I restart the server. 

Here is the message they get when trying to do a command:
http://prntscr.com/955kot
If they try to log out, they combat log and die.

No error seems to be present in console. I wish I could give you more information but from what I can see, there simply isn't. Please look in to this as it needs to be fixed. 

Running latest spigot 1.8.8
Running latest PvPManager 3.3.2

**Comment by NoChanceSD** [comment]
Weird, the plugin doesn't just skip a player so i would expect some error in console.

Did you happen to notice if the player's name was already red (or whatever prefix) before combat.

**Comment by LeDadSnatcher** [comment]
I did not as I have animatednames installed. I will continue to try it.

**Comment by LeDadSnatcher** [comment]
Just tried it and it happened again. I have found the error though which is brilliant :)

http://pastebin.com/Whi93cKe

Thanks.

**Comment by NoChanceSD** [comment]
Awesome, thanks.

**Comment by NoChanceSD** [comment]
Should be (partially) fixed in latest update, i think animatednames conflicts with pvpmanager nametags.
Let me know if there is another error.
