### ISSUE TITLE
Killer/Victim Specific Respawn Protection for Kill Abuse 

### ISSUE THREAD

**Issue by Ilinalta** [NoChanceSD/PvPManager-Issues#90]
First I'd like to thank you for this awesome plugin, worth the money and works excellently thus far.

My question is regarding the kill abuse settings and possible improvement of them. They're okay for limiting players and punishing them for going over the kill limit. But I'd personally rather not have to punish them at all.

My question is about the "respawn protection" option. Does that apply to all players, or just the player that killed them? In other words, if player X kills player Y, can another player, player Z, kill player Y, or is player Y immune to any/all PVP enabled players altogether?

What I'm looking to do is have it so that the respawn protection is only between player X and Y, so if one of them dies because the other killed them, and this happens over the max kills limit, they can still PVP with other players but cannot PVP with each other anymore. This then has its **own** countdown until they can pvp again. An example config:

Killer Victim Respawn Protection:
  Enabled: true
  KV Respawn Protection Time: 1800

Where it still uses the max kills amount, but this protection is specifically between the killer and victim only. The original respawn protection could still be used if it applies to all players, but this type of protection I feel would be more handy.

Many thanks!

**Comment by NoChanceSD** [comment]
Hello, the respawn protection does apply to all players, no plans to change that for now. Sorry for the delay.
