### ISSUE TITLE
Feature Request: PvP Per-Biome.

### ISSUE THREAD

**Issue by KnifeKat** [NoChanceSD/PvPManager-Issues#97]
Just wanted to ask if it was possible to do the following:

Make players unable to PVP unless they were in specific Biomes. With Per-Biome Permissions.

If someone has pvpmanager.deepocean - they could PVP in a Deep Ocean Biome. 

Makes it able to restrict the areas where PVP is, and is not enabled, instead of just the entire world itself.

It also gives a lot of customization as well(Races/Classes type Plugins for example or more.) To essentially make some players able to PVP in some Biomes while others could not. But, those who can PVP in specific biomes, can attack players who could not retaliate/fight back in those biomes.

Pretty much, most players in my server do not want to PVP. Sadly this server will have some form of PVP in one way or another.

I was going to make it where players can only PVP in Extreme Hills & Jungle Biomes. So players that really do not want to PVP, can stay out of those biomes, or risk being in those biomes if they really want to build there.

Making someone completely unable to be PVPed in all areas kills the excitement of seeing a player and wanting to kill them knowing they would never PVP. This gives players to opt out of PVP without just completely doing /pvp off and being out of PVP in the entire world. 

I may of explained this messy, but it would be really amazing if something like this could happen! <3

Maybe an option to enable/disable this option so users do not need to give all players permissions to PVP in all Biomes by default. 

Thank you in advance!

Possibility to add the ability to make permissions for custom Biomes with custom names. (Skyland Generator 2 for example.) - Could detect custom biome names and do that as well.

**Comment by NoChanceSD** [comment]
I don't know if you still have interest in this since it has been a while but even if you do i feel this would be better suited for an addon or other plugin as it's a very specific feature. Maybe it could be done with worldguard regions as well.
