### ISSUE TITLE
[Request] Ability to initiate Combat when hit by an enderpearl/arrow

### ISSUE THREAD

**Issue by TheFlagCourier** [NoChanceSD/PvPManager-Issues#98]
We recently switched to using PvPManager, and our previous tag system was configured to tag players when they received damage from Arrows and Ender Pearls thrown by another player. We got a report that ePearls and arrows were not triggering combat. Besides enabling the 'Any Damage' - I can't see a way to enable these.

**Comment by NoChanceSD** [comment]
This can be solved by setting "Ignore No Damage Hits" to false in the config.
